// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6357.SpringKonstant;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController baserightBackMotor;
    public static SpeedController baserightFrontMotor;
    public static SpeedController baseleftFrontMotor;
    public static SpeedController baseleftCenterMotor;
    public static SpeedController baseleftBackMotor;
    public static SpeedController baserightCenterMotor;
    public static SpeedController climbclimbMotor1;
    public static SpeedController climbclimbMotor2;
    public static Solenoid climbclimbSolenoid;
    public static Compressor climbclimbCompressor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        baserightBackMotor = new Talon(4);
        LiveWindow.addActuator("Base", "rightBackMotor", (Talon) baserightBackMotor);
        
        baserightFrontMotor = new Talon(3);
        LiveWindow.addActuator("Base", "rightFrontMotor", (Talon) baserightFrontMotor);
        
        baseleftFrontMotor = new Talon(0);
        LiveWindow.addActuator("Base", "leftFrontMotor", (Talon) baseleftFrontMotor);
        
        baseleftCenterMotor = new Talon(1);
        LiveWindow.addActuator("Base", "leftCenterMotor", (Talon) baseleftCenterMotor);
        
        baseleftBackMotor = new Talon(2);
        LiveWindow.addActuator("Base", "leftBackMotor", (Talon) baseleftBackMotor);
        
        baserightCenterMotor = new Talon(5);
        LiveWindow.addActuator("Base", "rightCenterMotor", (Talon) baserightCenterMotor);
        
        climbclimbMotor1 = new Talon(6);
        LiveWindow.addActuator("Climb", "climbMotor1", (Talon) climbclimbMotor1);
        
        climbclimbMotor2 = new Talon(7);
        LiveWindow.addActuator("Climb", "climbMotor2", (Talon) climbclimbMotor2);
        
        climbclimbSolenoid = new Solenoid(0, 0);
        LiveWindow.addActuator("Climb", "climbSolenoid", climbclimbSolenoid);
        
        climbclimbCompressor = new Compressor(0);
        
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
