// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6357.SpringKonstant.subsystems;

import org.usfirst.frc6357.SpringKonstant.RobotMap;
import org.usfirst.frc6357.SpringKonstant.commands.*;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveBaseSystem extends Subsystem // MARK: BreakPoint
{
    private final SpeedController frontLeft = RobotMap.baseFrontLeft;
    private final SpeedController centerLeft = RobotMap.baseCenterLeft;
    private final SpeedController backLeft = RobotMap.baseBackLeft;
    private final SpeedController frontRight = RobotMap.baseFrontRight;
    private final SpeedController centerRight = RobotMap.baseCenterRight;
    private final SpeedController backRight = RobotMap.baseBackRight;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() 
    {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void setLeftMotors(double speed)
    {
    	frontLeft.set(speed);
    	centerLeft.set(speed);
    	backLeft.set(speed);
    }
    
    public void setRightMotors(double speed)
    {
    	frontRight.set(speed);
    	centerRight.set(speed);
    	backRight.set(speed);
    	
    }
}

