// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6357.SpringKonstant;

import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap
{
   
    public static Solenoid gearSolenoid1;
    public static Solenoid gearSolenoid2;
    public static Solenoid gearSolenoid3;
    public static Solenoid gearSolenoid4;
    public static SpeedController baseFrontLeft;
    public static SpeedController baseCenterLeft;
    public static SpeedController baseBackLeft;
    public static SpeedController baseFrontRight;
    public static SpeedController baseCenterRight;
    public static SpeedController baseBackRight;


    public static void init() 
    {
    	
        gearSolenoid1 = new Solenoid(0, 0);											//Solenoid (int moduelNumber, int channel);
        LiveWindow.addActuator("Gear Placement", "Solenoid 1", gearSolenoid1);
        
        gearSolenoid2 = new Solenoid(0, 0);
        LiveWindow.addActuator("Gear Placement", "Solenoid 2", gearSolenoid2);
        
        gearSolenoid3 = new Solenoid(0, 0);
        LiveWindow.addActuator("Gear Placement", "Solenoid 3", gearSolenoid3);
        
        gearSolenoid4 = new Solenoid(0, 0);
        LiveWindow.addActuator("Gear Placement", "Solenoid 4", gearSolenoid4);
        
        baseFrontLeft = new Talon(4);
        LiveWindow.addActuator("Base", "FrontLeft", (Talon) baseFrontLeft);
        
        baseCenterLeft = new Talon(2);
        LiveWindow.addActuator("Base", "Center Left", (Talon) baseCenterLeft);
        
        baseBackLeft = new Talon(0);
        LiveWindow.addActuator("Base", "Back Left", (Talon) baseBackLeft);
        
        baseFrontRight = new Talon(5);
        LiveWindow.addActuator("Base", "FrontRight", (Talon) baseFrontRight);
        
        baseCenterRight = new Talon(3);
        LiveWindow.addActuator("Base", "CetnerRight", (Talon) baseCenterRight);
        
        baseBackRight = new Talon(1);
        LiveWindow.addActuator("Base", "Back Right", (Talon) baseBackRight);
        

    }
}
