// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6357.SpringKonstant;

import edu.wpi.first.wpilibj.Compressor;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc6357.SpringKonstant.subsystems.*;
import org.usfirst.frc6357.SpringKonstant.utility.GitRevisionEvaluator;

import com.analog.adis16448.frc.ADIS16448_IMU;
import com.ctre.CANTalon;
/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot 
{

    Command autonomousCommand;

    public static OI oi;
    
    // Subsystems
    //public static GearDeploymentSystem gearDeploymentSystem;
    public static RopeClimbSystem ropeClimbSystem;
    public static DriveBaseSystem driveBaseSystem;
    
    // Joysticks
    public static Joystick driver;
    public static Joystick operator;
    
    // Actuators
    public static DoubleSolenoid doubleSolenoid1;
    public static SpeedController baseFrontLeft;
    public static SpeedController baseCenterLeft;
    public static SpeedController baseBackLeft;
    public static SpeedController baseFrontRight;
    public static SpeedController baseCenterRight;
    public static SpeedController baseBackRight;
    public static Compressor compressor1;
    //encoders
    public static Encoder encoderLeft;
	public static Encoder encoderRight;
	private double wait;
	//gyroscope
	//public static ADIS16448_IMU myIMU;
	
	//Auto
	public static AutonomousMatchController auto;
	
	private double leftJoystickOffset;
	private double rightJoystickOffset;

	private final Timer myTimer = new Timer();
    
    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    public void robotInit() 
    {	
    	// Actuators
    	compressor1 = new Compressor(0);
    	LiveWindow.addActuator("Compressor", "Compressor", compressor1);
    	
        doubleSolenoid1 = new DoubleSolenoid(0, 0, 1);										
        LiveWindow.addActuator("Gear Placement", "Double Solenoid 1", doubleSolenoid1);
       
        
        
        //TALON SRX ASSIGNMENTS:
        // LEFT 10,11,15
        // RIGHT 12,14,16
        // THE TALONS ARE SET UP TO USE FOLLOWING, so we only need the front left and front right
        
        baseFrontLeft = new CANTalon(10);
        baseCenterLeft = new CANTalon(11);
        ((CANTalon)baseCenterLeft).changeControlMode(CANTalon.TalonControlMode.Follower);
        ((CANTalon)baseCenterLeft).set(((CANTalon)baseFrontLeft).getDeviceID());
        baseBackLeft = new CANTalon(15);
        ((CANTalon)baseBackLeft).changeControlMode(CANTalon.TalonControlMode.Follower);
        ((CANTalon)baseBackLeft).set(((CANTalon)baseFrontLeft).getDeviceID());
        
        baseFrontRight = new CANTalon(12);
        baseFrontRight.setInverted(true);
        baseCenterRight = new CANTalon(14);
        ((CANTalon)baseCenterRight).changeControlMode(CANTalon.TalonControlMode.Follower);
        ((CANTalon)baseCenterRight).set(((CANTalon)baseFrontRight).getDeviceID());
        baseBackRight = new CANTalon(16);
        ((CANTalon)baseBackRight).changeControlMode(CANTalon.TalonControlMode.Follower);
        ((CANTalon)baseBackRight).set(((CANTalon)baseFrontRight).getDeviceID());
    	
        //Encoders 
        encoderLeft = new Encoder(2, 3);
        encoderRight = new Encoder(0, 1);
        
        // IMPORTANT CONVENTION: ALWYAS FEET PER SECOND
        final double DistancePerPulse = (3.1415926539*4.0/12.0)/384.0;
        
        encoderLeft.setDistancePerPulse(DistancePerPulse);
        encoderRight.setDistancePerPulse(DistancePerPulse);
        
    	// Subsystems
    	//gearDeploymentSystem = new GearDeploymentSystem();
    	ropeClimbSystem = new RopeClimbSystem();
    	driveBaseSystem = new DriveBaseSystem(baseFrontLeft, baseFrontRight, encoderLeft, encoderRight);
        
    	//Auto
        //auto = new AutonomousMatchController(encoderRight, encoderLeft, driveBaseSystem);

    	
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // instantiate the command used for the autonomous period
        

        
        
    
        //GyroScope 
        //myIMU = new ADIS16448_IMU();
        //myIMU.reset();
        
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    public void disabledInit()
    {

    }

    public void disabledPeriodic() 
    {
        Scheduler.getInstance().run();
        SmartDashboard.putNumber("rvel", encoderRight.getRate());
        SmartDashboard.putNumber("lvel", encoderLeft.getRate());
        SmartDashboard.putNumber("rpos", encoderRight.getDistance());
        SmartDashboard.putNumber("lpos", encoderLeft.getDistance());
        SmartDashboard.putNumber("l_setpt", driveBaseSystem.GetLeftSpeedSetpoint());
        SmartDashboard.putNumber("r_setpt", driveBaseSystem.GetRightSpeedSetpoint());
        //SmartDashboard.putString("git revision", GitRevisionEvaluator.GetGitRevision());
        //SmartDashboard.putData("IMU", myIMU);
        driveBaseSystem.setLeftMotorSpeedPercent(0.0f);
        driveBaseSystem.setRightMotorSpeedPercent(0.0f);
    }

    public void autonomousInit() 
    {
        // schedule the autonomous command (example)
        //if (autonomousCommand != null) autonomousCommand.start();
        //gyro1.calibrate();
    	encoderRight.reset();
    	encoderLeft.reset();
    	driveBaseSystem.Enable();
    	driveBaseSystem.SetPositionMode();
    	myTimer.start();
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() 
    {
        Scheduler.getInstance().run();
        driveBaseSystem.DriveStraight(5);			//drives 5 feet forward
        
        if (driveBaseSystem.isRobotStopped())
        	wait = myTimer.get() + 2;
        
        if (myTimer.get() > wait)
        	driveBaseSystem.rotateRobot(90);		//rotates 90 degrees clockwise
        
        if (driveBaseSystem.isRobotStopped())
        	wait = myTimer.get() + 2;
        
        if (myTimer.get() > wait)
        	driveBaseSystem.DriveStraight(1);		//drives 1 foot to the right
        
        if (driveBaseSystem.isRobotStopped())
        	wait = myTimer.get() + 2;
        
        if (myTimer.get() > wait)
        	driveBaseSystem.rotateRobot(-450);		//rotates 450 degrees counter clockwise
        	
        if (driveBaseSystem.isRobotStopped())
        	wait = myTimer.get() + 2;
        
        if (myTimer.get() > wait)
        	driveBaseSystem.DriveStraight(-5);		//drives 5 feet backwards
        
        if (driveBaseSystem.isRobotStopped())
        	wait = myTimer.get() + 2;
        
        if (myTimer.get() > wait)
        	driveBaseSystem.rotateRobot(90);		//rotates 90 degrees clockwise
        
        if (driveBaseSystem.isRobotStopped())
        	wait = myTimer.get() + 2;
        
        if (myTimer.get() > wait)
        	driveBaseSystem.DriveStraight(-1);		//drives 1 foot backwards to the left
        
        if (driveBaseSystem.isRobotStopped())
        	wait = myTimer.get() + 2;
        
        if (myTimer.get() > wait)
        	driveBaseSystem.rotateRobot(-90);		//rotates 90 degrees counter clockwise
        
        	
        //driveBaseSystem.rotateRobot(45);
        //driveBaseSystem.DriveStraight(10.0f);
        
        SmartDashboard.putNumber("rvel", encoderRight.getRate());
        SmartDashboard.putNumber("lvel", encoderLeft.getRate());
        SmartDashboard.putNumber("rpos", encoderRight.getDistance());
        SmartDashboard.putNumber("lpos", encoderLeft.getDistance());
        SmartDashboard.putNumber("l_setpt", driveBaseSystem.GetLeftSpeedSetpoint());
        SmartDashboard.putNumber("r_setpt", driveBaseSystem.GetRightSpeedSetpoint());
        SmartDashboard.putNumber("l_drive", baseFrontLeft.get());
        SmartDashboard.putNumber("r_drive", baseFrontRight.get());
    }

    public void teleopInit() 
    {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
        
        driver = oi.getDriver();
        operator = oi.getOperator();
        //compressor1.start();
        //compressor1.enabled();
        driveBaseSystem.SetVelocityMode();
        driveBaseSystem.setLeftMotorSpeedPercent(0.0f);
        driveBaseSystem.setRightMotorSpeedPercent(0.0f);
        leftJoystickOffset = driver.getRawAxis(1);
        rightJoystickOffset = driver.getRawAxis(5);
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() 
    {
        Scheduler.getInstance().run();
        
        double leftDrive = driver.getRawAxis(1);
        double rightDrive = driver.getRawAxis(5);
        if(Math.abs(leftDrive) < 0.07){
        	leftDrive = 0.0;
        }
        if(Math.abs(rightDrive) < 0.07){
        	rightDrive = 0.0;
        }
        driveBaseSystem.setLeftMotorSpeedPercent(leftDrive);
        driveBaseSystem.setRightMotorSpeedPercent(rightDrive);
        
        SmartDashboard.putNumber("rvel", encoderRight.getRate());
        SmartDashboard.putNumber("lvel", encoderLeft.getRate());
        SmartDashboard.putNumber("rpos", encoderRight.getDistance());
        SmartDashboard.putNumber("lpos", encoderLeft.getDistance());
        
        SmartDashboard.putNumber("l_setpt", driveBaseSystem.GetLeftSpeedSetpoint());
        SmartDashboard.putNumber("r_setpt", driveBaseSystem.GetRightSpeedSetpoint());
        SmartDashboard.putNumber("l_drive", baseFrontLeft.get());
        SmartDashboard.putNumber("r_drive", baseFrontRight.get());
    
    }

    /**
     * This function is called periodically during test mode
     */
    public void testPeriodic() 
    {
        LiveWindow.run();
    }
}
