// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6357.SpringKonstant.commands;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6357.SpringKonstant.Robot;
import org.usfirst.frc6357.SpringKonstant.RobotMap;

/**
 *
 */
public class GearPlacement extends Command 
{
	
	private final Solenoid solenoid1 = RobotMap.gearSolenoid1;
	private final Solenoid solenoid2 = RobotMap.gearSolenoid2;
	private final Solenoid solenoid3 = RobotMap.gearSolenoid3;
	private final Solenoid solenoid4 = RobotMap.gearSolenoid4;
	
    public GearPlacement() 
    {
        requires(Robot.gearDeploymentSystem);
    }

    // Called just before this Command runs the first time
    protected void initialize() 
    {
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() 
    {
    	solenoid1.set(true);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() 
    {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() 
    {
    	
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() 
    {
    	
    }
}
